routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('login/user/{provider}', [App\Http\Controllers\UserController::class, 'userLogin']);
Route::get('login/broker/{provider}', [App\Http\Controllers\UserController::class, 'brokerLogin']);
Route::get('login/expert/{provider}', [App\Http\Controllers\UserController::class, 'expertLogin']);

Route::get('login/{provider}/callback', [App\Http\Controllers\UserController::class, 'handleProviderCallback']);

Route::post('/signupOtp', [App\Http\Controllers\UserController::class, 'SendOtp'])->name('signupOtp');
Route::post('/userSignup', [App\Http\Controllers\UserController::class, 'userSignup'])->name('userSignup');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buy', [App\Http\Controllers\HomeController::class, 'showBuy'])->name('buy');
Route::post('/sendemail', [App\Http\Controllers\HomeController::class, 'sendEmail'])->name('sendemail');
Route::any('/buy-your-land', [App\Http\Controllers\HomeController::class, 'showBuyYourLand'])->name('buyyourland');
Route::get('/sell-your-land', [App\Http\Controllers\HomeController::class, 'showSellYourLand'])->name('sellyourland');
Route::get('/feasibility-analysis', [App\Http\Controllers\HomeController::class, 'showFeasibilityAnalysis'])->name('feasibilityanalysis');
Route::get('/land-title-search', [App\Http\Controllers\HomeController::class, 'showLandTitleSearch'])->name('landtitlesearch');
Route::get('/aboutus', [App\Http\Controllers\HomeController::class, 'showAboutUs'])->name('aboutus');

Route::get('/meet-the-expert', [App\Http\Controllers\HomeController::class, 'ShowMeetTheExpert'])->name('meettheexpert');
Route::get('/terms-conditions', [App\Http\Controllers\HomeController::class, 'ShowTermsConditions'])->name('termsconditions');
Route::get('/privacy-policy', [App\Http\Controllers\HomeController::class, 'ShowPrivacyPolicy'])->name('privacypolicy');
Route::get('/cookie-policy', [App\Http\Controllers\HomeController::class, 'ShowCookiePolicy'])->name('cookiepolicy');
Route::get('/land-report-anlysis-form', [App\Http\Controllers\HomeController::class, 'ShowLandReportAnlysisForm'])->name('landreportanlysisform');
Route::any('/land-title-search-form', [App\Http\Controllers\HomeController::class, 'ShowLandTitleSearchForm'])->name('landtitlesearchform');
Route::get('/book-your-appointment', [App\Http\Controllers\HomeController::class, 'ShowBookYourAppointment'])->name('bookyourappointment');
Route::get('/login', [App\Http\Controllers\UserController::class, 'showLogin'])->name('login');
Route::post('/storeexpert', [App\Http\Controllers\UserController::class, 'storeExpert'])->name('storeexpert');
Route::post('/storebroker', [App\Http\Controllers\UserController::class, 'storeBroker'])->name('storebroker');
// sell lend routing
Route::get('/sell-your-land', [App\Http\Controllers\HomeController::class, 'sellland'])->name('sellland');
Route::post('/sell-your-land-form', [App\Http\Controllers\HomeController::class, 'selllandform'])->name('selllandform');
Route::post('/store_property', [App\Http\Controllers\HomeController::class, 'storeproperty'])->name('store_property');
Route::get('/sign-up', [App\Http\Controllers\UserController::class, 'showSignUp'])->name('signup');

//03-05-2021
Route::post('/store_property_validation', [App\Http\Controllers\HomeController::class, 'storePropertyValidation']);

Route::post('/store-land-appointment', [App\Http\Controllers\HomeController::class, 'LandAppointmentStore'])->name('store-land-appointment');
Route::post('/store_appointment_validation', [App\Http\Controllers\HomeController::class, 'LandAppointmentValidition']);
// by vaishnavi
Route::post('/store-services', [App\Http\Controllers\HomeController::class, 'storeServices'])->name('store-services');
//by vaishnavi 25/03/21
Route::post('/agent-contacts', [App\Http\Controllers\HomeController::class, 'agentContact']);
//23-04-2021
Route::post('/generate-land-report-payment-token', [App\Http\Controllers\HomeController::class, 'paymentTokenGenerate']);

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->route('admin.dashboard');
    }
    return view('admin/login');
})->name('admin-login');

Route::post('/admin/adminlogin', [App\Http\Controllers\admin\AdminLoginController::class, 'doAdminLogin'])->name('adminlogin');
// send OTP to user
Route::post('/sendOtp', [App\Http\Controllers\UserController::class, 'doSendOtp'])->name('sendOtp');
Route::post('/login', [App\Http\Controllers\UserController::class, 'doLogin'])->name('login');
/* Route::get('/admin/dashboard', function() {
  return view('admin/dashboard');
  })->name('admin.dashboard'); */

Route::prefix('admin')->middleware(['auth', 'role:admin'])->name('admin.')->group(function () {

    Route::any('/dashboard', [App\Http\Controllers\admin\DashboardController::class, 'index'])->name('dashboard');

    Route::any('/experts/{search?}', [App\Http\Controllers\admin\ExpertController::class, 'index'])->name('experts');
    Route::any('/value-added-services/{search?}', [App\Http\Controllers\admin\ValueAddedServiceController::class, 'valueAddedServices'])->name('value-added-services');

    Route::any('/pendingexperts', [App\Http\Controllers\admin\ExpertController::class, 'showPendingExperts'])->name('showpendingexperts');

    Route::post('/delete-pendingexpert', [App\Http\Controllers\admin\ExpertController::class, 'destroyPendingExperts'])->name('delete-pendingexpert');

    Route::get('/get-expert/{id}', [App\Http\Controllers\admin\ExpertController::class, 'edit'])->name('get-expert');

    Route::post('/update-expert/', [App\Http\Controllers\admin\ExpertController::class, 'update'])->name('update-expert');
    Route::get('/approve-expert/{id}', [App\Http\Controllers\admin\ExpertController::class, 'approveExpert'])->name('approve-expert');

    Route::get('/addvalue', function () {
        return view('admin/addvalue');
    })->name('addvalue');

    Route::resource('valueservices', App\Http\Controllers\admin\ValueAddedServiceController::class);
    Route::post('/assign-expert-popup', [App\Http\Controllers\admin\ReportController::class, 'getExpertPopup'])->name('reports');
    Route::any('/appointments', [App\Http\Controllers\admin\AppointmentController::class, 'index'])->name('appointments');
    Route::any('/reports', [App\Http\Controllers\admin\ReportController::class, 'index'])->name('reports');
    // by vaishnavi 
    Route::any('/land-listing', [App\Http\Controllers\admin\LandListingController::class, 'index'])->name('land-listing');

    Route::any('/payments', [App\Http\Controllers\admin\PaymentController::class, 'index'])->name('payments');
    // 27-04-2021
    Route::post('/user-payment-store', [App\Http\Controllers\admin\PaymentController::class, 'userPaymentStore']);
    Route::post('/user-name-autosuggest', [App\Http\Controllers\admin\PaymentController::class, 'userNameAutoSuggest'])->name('user-name-autosuggest');
    Route::any('/rating-and-review', [App\Http\Controllers\admin\RatingReviewController::class, 'index'])->name('rating-and-review');
    Route::any('/messages', [App\Http\Controllers\admin\MessageController::class, 'index'])->name('messages');
    Route::get('/your-profile', [App\Http\Controllers\admin\ProfileController::class, 'index'])->name('your-profile');

//        16-03-2021
    Route::post('/user-email-autosuggest', [App\Http\Controllers\admin\MessageController::class, 'userEmailAutoSuggest']);
    Route::post('/messages-send', [App\Http\Controllers\admin\MessageController::class, 'messageSend']);

//    18-03-2021
    Route::post('/profile-update', [App\Http\Controllers\admin\ProfileController::class, 'profileUpdate']);
    Route::post('/upload_admin_photo', [App\Http\Controllers\admin\ProfileController::class, 'profilePhotoUpload']);

//    24-03-2021
    Route::post('/assign-to-expert', [App\Http\Controllers\admin\AppointmentController::class, 'assignToExpert']);

//    19-03-2021
    Route::any('/pages', [App\Http\Controllers\admin\PageController::class, 'index']);
    Route::get('/page-create', [App\Http\Controllers\admin\PageController::class, 'create']);
    Route::post('/page-store', [App\Http\Controllers\admin\PageController::class, 'store']);
    Route::post('/imageUpload', [App\Http\Controllers\admin\PageController::class, 'imageUpload']);
    Route::get('/edit-page/{slug}', [App\Http\Controllers\admin\PageController::class, 'editPage']);
    Route::post('/update-page', [App\Http\Controllers\admin\PageController::class, 'updatePage']);
    Route::get('/delete-page/{id}', [App\Http\Controllers\admin\PageController::class, 'deletePage']);

//    23-03-2021
    Route::get('/appointment-details', [App\Http\Controllers\admin\AppointmentController::class, 'appointmentDetails']);

//    25-03-2021
    Route::any('/active-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'activeLandListing']);
    Route::any('/inactive-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'inActiveListing']);
    Route::any('/request-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'requestListing']);

    Route::get('/adminlogout', [App\Http\Controllers\admin\AdminLoginController::class, 'doAdminLogout'])->name('adminlogout');

//    26-03-2021
    Route::post('/view-all-appointment', [App\Http\Controllers\admin\AppointmentController::class, 'viewAllAppointment']);

resources/views/admin/addvalue.blade.php
@extends('admin.layouts.master')
@section('title')
  Experts
@endsection
@section('content')
<h2>Value added services</h2>
@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
           <form id="frm_value_added_service" method="POST" enctype="multipart/form-data" action="{{ route('admin.valueservices.store') }}">
            @csrf
            <ul class="d-flex flex-wrap form-fields" id="services-inline-popups">
                <li>
                    <div class="form-group">
                        <input type="text" class="form-control" name="service_name" placeholder="Service Name" id="service_name">
                         @if ($errors->has('service_name'))
                             <span class="invalid-feedback" role="alert">{{ $errors->first('service_name') }}</span>
                        @endif
                    </div><!-- //form-group -->
                </li>
                <li>
                    <div class="form-group">
                        <textarea class="form-control" rows="3" placeholder="Service Description" name="description" id="description"></textarea>
                    </div><!-- //form-group -->
                </li>
                <li>
                    <div class="custom-file">
                        <input type="file" class="custom-file-input" name="service_icon" id="service_icon">
                        <label class="custom-file-label" for="service_icon">Service Icon</label>
                    </div>
                </li>
                <li>
                     <button type="submit" class="btn btn-primary w-100 mt-4">Add Services</button>
                </li>
            </ul><!-- //ul -->
           </form>
 @endsection

resources/views/admin/dashboard.blade.php
@extends('admin.layouts.master')
@section('title')
Admin Dashboard
@endsection
@section('content')

<div class="pageTitle">
	<h1>Dashboard</h1> 
</div>

<div class="countCards">
    <div class="row">
        <div class="col-lg-4 col-md-6">
            <article class="countCardArt">
                <div class="coutRepIcon">
                    <img src="{{ asset('adminassets/images/svg-icons/appointments-icon.svg') }}" alt="All Appointments" />
                </div>
                <div class="countRepDetail">
                    <p><strong>{{ $total_app->count()}}</strong></p>
                    <p>All Appointments</p>
                </div>
            </article><!--//countCardArt-->
        </div><!--//col-lg-4-->

        <div class="col-lg-4 col-md-6">
            <article class="countCardArt">
                <div class="coutRepIcon">
                    <img src="{{ asset('adminassets/images/svg-icons/listing-icon.svg') }}" alt="All Land Listing" />                                    
                </div>
                <div class="countRepDetail">
                    <p><strong>{{ $total_land->count()}}</strong></p>
                    <p>All Land Listing</p>
                </div>
            </article><!--//countCardArt-->
        </div><!--//col-lg-4-->

        <div class="col-lg-4 col-md-6">
            <article class="countCardArt">
                <div class="coutRepIcon">
                    <img src="{{ asset('adminassets/images/svg-icons/admin-reports-icon.svg') }}" alt="All Reports" />                                    
                </div>
                <div class="countRepDetail">
                    <p><strong>{{ $total_report->count()}}</strong></p>
                    <p>All Reports</p>
                </div>
            </article><!--//countCardArt-->
        </div><!--//col-lg-4-->                       
    </div><!--//row-->
</div><!--//countCards-->

<div class="div-repeat d-none">
    <div class="pageTitle d-flex align-items-center">
        <h3>Appointments</h3>
        
        <div class="sortDropdown">
            <label>Show by</label>
            <div class="dropdown custom-dropdown">
                <a href="javascript:void(0);" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    <span class="selected">{{$filterDate}}</span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#" class="expertPaginate" data-value="week">Week</a></li>
                    <li><a href="#" class="expertPaginate" data-value="month">Month</a></li>
                    <li><a href="#" class="expertPaginate" data-value="year">Year</a></li>
                </ul>
            </div><!-- //dropdown --> 
        </div><!--//sortDropdown-->
    </div><!--//pageTitle-->
 
    <div class="graphDiv border">
        <canvas id="myChart" width="400" height="300"></canvas>
    </div> 
</div><!--//div-repeat -->

<div class="div-repeat d-none">
    <div class="pageTitle d-flex align-items-center">
        <h3>Land Listing</h3>
        
        <!--
        <div class="sortDropdown">
            <label>Show by</label>
            <div class="dropdown custom-dropdown">
                <a href="javascript:void(0);" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    <span class="selected">Month</span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#">Week</a></li>
                    <li><a href="#">Month</a></li>
                    <li><a href="#">Year</a></li>
                </ul>
            </div>
        </div>
        --> 
    </div><!--//pageTitle-->
 
    <div class="graphDiv border">
        <canvas id="landdetailChart" width="400" height="300"></canvas>
    </div> 
</div><!--//div-repeat -->

<div class="div-repeat d-none">
    <div class="pageTitle d-flex align-items-center">
        <h3>Reports</h3>
        
        <!--
        <div class="sortDropdown">
            <label>Show by</label>
            <div class="dropdown custom-dropdown">
                <a href="javascript:void(0);" aria-expanded="false" aria-haspopup="true" role="button" data-toggle="dropdown" class="dropdown-toggle">
                    <span class="selected">Month</span><span class="caret"></span>
                </a>
                <ul class="dropdown-menu dropdown-menu-right">
                    <li><a href="#">Week</a></li>
                    <li><a href="#">Month</a></li>
                    <li><a href="#">Year</a></li>
                </ul>
            </div> 
        </div>
        --> 
    </div><!--//pageTitle--> 

    <div class="graphDiv border d-none">
        <canvas id="landreportChart" width="400" height="300"></canvas>
    </div> 
</div><!--//div-repeat --> 

<form method="post" id="paginateSubmitForm">
    @csrf
    <input type="hidden" name="day" id="paginateHiddenFiled">
</form>
@endsection
@section('custom-script')
<script>
$('.expertPaginate').on('click', function (e) {
e.preventDefault();
var value = $(this).data('value');
$('#paginateHiddenFiled').val(value);
$('#paginateSubmitForm').submit();
return false;
});
window.onload = function () {
// Admin appointment chart show
var ctx = document.getElementById('myChart').getContext('2d');
var myChart = new Chart(ctx, {
type: 'line',
        data: {
        labels: {!! $adminEarningDate !!},
                datasets: [{
                label: "{!! $doneAppointmentTitle !!}",
                        data: {!! $adminEarningAmount !!},
                        backgroundColor: 'transparent',
                        borderColor: "#4bc0c0",
                        fill: true,
                        borderWidth: 2
                },
                {
                label: "{!! $pendingAppointmentTitle !!}",
                        data: {!! $pendingAppointment !!},
                        backgroundColor: 'transparent',
                        borderColor: "#ff6384",
                        fill: true,
                        borderWidth: 2
                },
                ]
        },
        options: {
        scales: {
        yAxes: [{
        ticks: {
        beginAtZero:true
        }
        }]
        }
        }
});
// Admin land chart show
var ctx = document.getElementById('landdetailChart').getContext('2d');
var myChart = new Chart(ctx, {
type: 'line',
        data: {
        labels: {!! $landVerifiedDate !!},
                datasets: [{
                label: "verified lands",
                        data: {!! $landVerifiedDeatil !!},
                        backgroundColor: 'transparent',
                        borderColor: "#4bc0c0",
                        fill: true,
                        borderWidth: 2
                },
                {
                label: "Not verified lands",
                        data: {!! $landUnverifiedDeatil !!},
                        backgroundColor: 'transparent',
                        borderColor: "#ff6384",
                        fill: true,
                        borderWidth: 2
                },
                ]
        },
        options: {
        scales: {
        yAxes: [{
        ticks: {
        beginAtZero:true
        }
        }]
        }
        }
});

// Admin report chart show
var ctx = document.getElementById('landreportChart').getContext('2d');
var myChart = new Chart(ctx, {
type: 'line',
        data: {
        labels: {!! $reportDeliveredDate !!},
                datasets: [{
                label: "Delivered reports",
                        data: {!! $reportDeliveredDeatil !!},
                        backgroundColor: 'transparent',
                        borderColor: "#4bc0c0",
                        fill: true,
                        borderWidth: 2
                },
                {
                label: "Pending reports",
                        data: {!! $reportPendingDeatil !!},
                        backgroundColor: 'transparent',
                        borderColor: "#ff6384",
                        fill: true,
                        borderWidth: 2
                },
                ]
        },
        options: {
        scales: {
        yAxes: [{
        ticks: {
        beginAtZero:true
        }
        }]
        }
        }
});
};

</script>
@endsection

resources/views/admin/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
@section('title')
  Admin Login
@endsection
@include('admin.partials.head')
<link rel="stylesheet" type="text/css" href="{{ asset('css/responsive.css?v=2.1') }}">
</head>
<body>  

<div class="adminLoginWrapper"> 
        <div class="leftloginBanner">
            <div class="adminLoginTitle">
                <h2>Making every <br>
                    <strong>square yard count</strong></h2>
            </div>
        </div>
        <div class="rightadminLoginSection">
            
            <!--//Login section-->
            <section class="adminLoginBox shown" id="admin_login"> 
                <div class="ad_logo">
                    <a href="{{ route('admin-login') }}"> 
                        <img src="{{ asset('images/logo-black.svg') }}" alt="logo">
                        Know your Land
                    </a>
                </div><!--//logo-->
        <form  class=""  method="POST"   action="{{ route('adminlogin') }}" >
             @csrf
            @if ($errors->any())
            <p class="text-center font-semibold text-danger my-3">
                @if ($errors->has('email'))
                    {{ $errors->first('email') }}
                @else
                    {{ $errors->first('password') }}
                @endif
                </p>
            @endif
                <div class="adminLoginForm">
                    <div class="form-group {{ $errors->has('email') ? ' has-error' : '' }}">
                        <label>Username</label>
                        <input type="text" placeholder="Type your Username" class="form-control" type="email" id="email" name="email" value="{{ old('email') }}" required autofocus/>
                         @if ($errors->has('email'))
                            <span class="invalid-feedback" role="alert">{{ $errors->first('email') }}</span>
                        @endif
                    </div>

                    <div class="form-group {{ $errors->has('password') ? ' has-error' : '' }}">
                        <label>Password</label>
                        <input type="password" placeholder="Enter your Password" class="form-control" name="password" id="password" />
                        @error('password')
                         <span class="invalid-feedback" role="alert">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="row align-items-center">
                        <div class="col-7">
                            <a href="javascript:void(0);" class="font_12" onclick="gotoSection('admin_forgot');">Forgot Password ?</a>
                        </div>
                        <div class="col-5 text-right adminLoginBtn">
                            
                                <button class="btn btn-primary" type="submit">Login</button>
                            
                        </div>
                    </div>
                </div><!--//adminLoginForm--> 
</form>

            </section><!--//adminLoginBox-->

            
            <!--//forgot section-->
            <div class="backBtn_forgot">
                <a href="javascript:void(0);" class="ad_backLogin" onclick="gotoSection('admin_login');"></a>
                <span>Forgot Password</span>
            </div>
            <section class="adminLoginBox" id="admin_forgot"> 
                <div class="ad_logo">
                    <a href="index.html"> 
                        <img src="{{ asset('images/logo-black.svg') }}" alt="logo">
                        Know your Land
                    </a>
                </div><!--//logo-->

                <div class="adminLoginForm">
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" placeholder="Enter your Email" class="form-control" />
                    </div> 

                    <div class="row align-items-center">
                        <div class="col-12 adminLoginBtn mb-3">
                            <button class="btn btn-primary" onclick="gotoSection('admin_reset');">Send a Link</button>
                        </div>

                        <div class="col-12 text-center">
                            <a href="javascript:void(0);" class="font_12">Resend Link</a>
                        </div>
                    </div>
                </div><!--//adminLoginForm--> 
            </section><!--//adminLoginBox-->

            
            <!--//Reset password section-->
            <section class="adminLoginBox" id="admin_reset"> 
                <div class="ad_logo">
                    <a href="index.html"> 
                        <img src="{{ asset('images/logo-black.svg') }}" alt="logo">
                        Know your Land
                    </a>
                </div><!--//logo-->

                <div class="adminLoginForm">
                    <div class="form-group">
                        <label>Password</label>
                        <input type="password" placeholder="Enter your Password" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label>Confirm Password</label>
                        <input type="password" placeholder="Enter your Confirm Password" class="form-control" />
                    </div>

                    <div class="row align-items-center"> 
                        <div class="col-12 adminLoginBtn">
                            <button class="btn btn-primary">Save Changes</button>
                        </div>
                    </div>
                </div><!--//adminLoginForm--> 
            </section><!--//adminLoginBox-->

        </div><!--//rightadminLoginSection-->
    </div><!--//adminLoginWrapper-->   
 
    <script type="text/javascript" src="{{ asset('js/jquery.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/bootstrap.min.js') }}"></script>    

    <script type="text/javascript"> 
        function gotoSection(section){ 
            $('.adminLoginBox').removeClass('shown');
            $('#'+section).addClass('shown');
            
            if(section=='admin_forgot'){
                $('.backBtn_forgot').addClass('shown');
            }else{
                $('.backBtn_forgot').removeClass('shown');
            }
        }
    </script>
 
</body>
</html>