routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */

Route::get('login/user/{provider}', [App\Http\Controllers\UserController::class, 'userLogin']);
Route::get('login/broker/{provider}', [App\Http\Controllers\UserController::class, 'brokerLogin']);
Route::get('login/expert/{provider}', [App\Http\Controllers\UserController::class, 'expertLogin']);

Route::get('login/{provider}/callback', [App\Http\Controllers\UserController::class, 'handleProviderCallback']);

Route::post('/signupOtp', [App\Http\Controllers\UserController::class, 'SendOtp'])->name('signupOtp');
Route::post('/userSignup', [App\Http\Controllers\UserController::class, 'userSignup'])->name('userSignup');

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('/buy', [App\Http\Controllers\HomeController::class, 'showBuy'])->name('buy');
Route::post('/sendemail', [App\Http\Controllers\HomeController::class, 'sendEmail'])->name('sendemail');
Route::any('/buy-your-land', [App\Http\Controllers\HomeController::class, 'showBuyYourLand'])->name('buyyourland');
Route::get('/sell-your-land', [App\Http\Controllers\HomeController::class, 'showSellYourLand'])->name('sellyourland');
Route::get('/feasibility-analysis', [App\Http\Controllers\HomeController::class, 'showFeasibilityAnalysis'])->name('feasibilityanalysis');
Route::get('/land-title-search', [App\Http\Controllers\HomeController::class, 'showLandTitleSearch'])->name('landtitlesearch');
Route::get('/aboutus', [App\Http\Controllers\HomeController::class, 'showAboutUs'])->name('aboutus');

Route::get('/meet-the-expert', [App\Http\Controllers\HomeController::class, 'ShowMeetTheExpert'])->name('meettheexpert');
Route::get('/terms-conditions', [App\Http\Controllers\HomeController::class, 'ShowTermsConditions'])->name('termsconditions');
Route::get('/privacy-policy', [App\Http\Controllers\HomeController::class, 'ShowPrivacyPolicy'])->name('privacypolicy');
Route::get('/cookie-policy', [App\Http\Controllers\HomeController::class, 'ShowCookiePolicy'])->name('cookiepolicy');
Route::get('/land-report-anlysis-form', [App\Http\Controllers\HomeController::class, 'ShowLandReportAnlysisForm'])->name('landreportanlysisform');
Route::any('/land-title-search-form', [App\Http\Controllers\HomeController::class, 'ShowLandTitleSearchForm'])->name('landtitlesearchform');
Route::get('/book-your-appointment', [App\Http\Controllers\HomeController::class, 'ShowBookYourAppointment'])->name('bookyourappointment');
Route::get('/login', [App\Http\Controllers\UserController::class, 'showLogin'])->name('login');
Route::post('/storeexpert', [App\Http\Controllers\UserController::class, 'storeExpert'])->name('storeexpert');
Route::post('/storebroker', [App\Http\Controllers\UserController::class, 'storeBroker'])->name('storebroker');
// sell lend routing
Route::get('/sell-your-land', [App\Http\Controllers\HomeController::class, 'sellland'])->name('sellland');
Route::post('/sell-your-land-form', [App\Http\Controllers\HomeController::class, 'selllandform'])->name('selllandform');
Route::post('/store_property', [App\Http\Controllers\HomeController::class, 'storeproperty'])->name('store_property');
Route::get('/sign-up', [App\Http\Controllers\UserController::class, 'showSignUp'])->name('signup');

//03-05-2021
Route::post('/store_property_validation', [App\Http\Controllers\HomeController::class, 'storePropertyValidation']);

Route::post('/store-land-appointment', [App\Http\Controllers\HomeController::class, 'LandAppointmentStore'])->name('store-land-appointment');
Route::post('/store_appointment_validation', [App\Http\Controllers\HomeController::class, 'LandAppointmentValidition']);
// by vaishnavi
Route::post('/store-services', [App\Http\Controllers\HomeController::class, 'storeServices'])->name('store-services');
//by vaishnavi 25/03/21
Route::post('/agent-contacts', [App\Http\Controllers\HomeController::class, 'agentContact']);
//23-04-2021
Route::post('/generate-land-report-payment-token', [App\Http\Controllers\HomeController::class, 'paymentTokenGenerate']);

Route::get('/admin', function () {
    if (Auth::check()) {
        return redirect()->route('admin.dashboard');
    }
    return view('admin/login');
})->name('admin-login');

Route::post('/admin/adminlogin', [App\Http\Controllers\admin\AdminLoginController::class, 'doAdminLogin'])->name('adminlogin');
// send OTP to user
Route::post('/sendOtp', [App\Http\Controllers\UserController::class, 'doSendOtp'])->name('sendOtp');
Route::post('/login', [App\Http\Controllers\UserController::class, 'doLogin'])->name('login');
/* Route::get('/admin/dashboard', function() {
  return view('admin/dashboard');
  })->name('admin.dashboard'); */

Route::prefix('admin')->middleware(['auth', 'role:admin'])->name('admin.')->group(function () {

    Route::any('/dashboard', [App\Http\Controllers\admin\DashboardController::class, 'index'])->name('dashboard');

    Route::any('/experts/{search?}', [App\Http\Controllers\admin\ExpertController::class, 'index'])->name('experts');
    Route::any('/value-added-services/{search?}', [App\Http\Controllers\admin\ValueAddedServiceController::class, 'valueAddedServices'])->name('value-added-services');

    Route::any('/pendingexperts', [App\Http\Controllers\admin\ExpertController::class, 'showPendingExperts'])->name('showpendingexperts');

    Route::post('/delete-pendingexpert', [App\Http\Controllers\admin\ExpertController::class, 'destroyPendingExperts'])->name('delete-pendingexpert');

    Route::get('/get-expert/{id}', [App\Http\Controllers\admin\ExpertController::class, 'edit'])->name('get-expert');

    Route::post('/update-expert/', [App\Http\Controllers\admin\ExpertController::class, 'update'])->name('update-expert');
    Route::get('/approve-expert/{id}', [App\Http\Controllers\admin\ExpertController::class, 'approveExpert'])->name('approve-expert');

    Route::get('/addvalue', function () {
        return view('admin/addvalue');
    })->name('addvalue');

    Route::resource('valueservices', App\Http\Controllers\admin\ValueAddedServiceController::class);
    Route::post('/assign-expert-popup', [App\Http\Controllers\admin\ReportController::class, 'getExpertPopup'])->name('reports');
    Route::any('/appointments', [App\Http\Controllers\admin\AppointmentController::class, 'index'])->name('appointments');
    Route::any('/reports', [App\Http\Controllers\admin\ReportController::class, 'index'])->name('reports');
    // by vaishnavi 
    Route::any('/land-listing', [App\Http\Controllers\admin\LandListingController::class, 'index'])->name('land-listing');

    Route::any('/payments', [App\Http\Controllers\admin\PaymentController::class, 'index'])->name('payments');
    // 27-04-2021
    Route::post('/user-payment-store', [App\Http\Controllers\admin\PaymentController::class, 'userPaymentStore']);
    Route::post('/user-name-autosuggest', [App\Http\Controllers\admin\PaymentController::class, 'userNameAutoSuggest'])->name('user-name-autosuggest');
    Route::any('/rating-and-review', [App\Http\Controllers\admin\RatingReviewController::class, 'index'])->name('rating-and-review');
    Route::any('/messages', [App\Http\Controllers\admin\MessageController::class, 'index'])->name('messages');
    Route::get('/your-profile', [App\Http\Controllers\admin\ProfileController::class, 'index'])->name('your-profile');

//        16-03-2021
    Route::post('/user-email-autosuggest', [App\Http\Controllers\admin\MessageController::class, 'userEmailAutoSuggest']);
    Route::post('/messages-send', [App\Http\Controllers\admin\MessageController::class, 'messageSend']);

//    18-03-2021
    Route::post('/profile-update', [App\Http\Controllers\admin\ProfileController::class, 'profileUpdate']);
    Route::post('/upload_admin_photo', [App\Http\Controllers\admin\ProfileController::class, 'profilePhotoUpload']);

//    24-03-2021
    Route::post('/assign-to-expert', [App\Http\Controllers\admin\AppointmentController::class, 'assignToExpert']);

//    19-03-2021
    Route::any('/pages', [App\Http\Controllers\admin\PageController::class, 'index']);
    Route::get('/page-create', [App\Http\Controllers\admin\PageController::class, 'create']);
    Route::post('/page-store', [App\Http\Controllers\admin\PageController::class, 'store']);
    Route::post('/imageUpload', [App\Http\Controllers\admin\PageController::class, 'imageUpload']);
    Route::get('/edit-page/{slug}', [App\Http\Controllers\admin\PageController::class, 'editPage']);
    Route::post('/update-page', [App\Http\Controllers\admin\PageController::class, 'updatePage']);
    Route::get('/delete-page/{id}', [App\Http\Controllers\admin\PageController::class, 'deletePage']);

//    23-03-2021
    Route::get('/appointment-details', [App\Http\Controllers\admin\AppointmentController::class, 'appointmentDetails']);

//    25-03-2021
    Route::any('/active-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'activeLandListing']);
    Route::any('/inactive-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'inActiveListing']);
    Route::any('/request-land-listing', [App\Http\Controllers\admin\LandListingController::class, 'requestListing']);

    Route::get('/adminlogout', [App\Http\Controllers\admin\AdminLoginController::class, 'doAdminLogout'])->name('adminlogout');

//    26-03-2021
    Route::post('/view-all-appointment', [App\Http\Controllers\admin\AppointmentController::class, 'viewAllAppointment']);

resources/views/admin/partials/footer.blade.php
<p><a href="javscript:void(0);">Terms Of Service</a>  |  <a href="javscript:void(0);">Privacy Policy</a><br>
                    Copyright &copy; {{ date('Y') }} {{ config('app.name', 'Exceedo') }}. All rights reserved.</p>

resources/views/admin/partials/head.blade.php
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ config('app.name', 'Exceedo') }} &#8211; @yield('title')</title>
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/bootstrap.min.css') }}">

<!-- //Magnific Popup Css -->
<link rel="stylesheet" href="{{ asset('adminassets/css/magnific-popup.css') }}">
@if( Request::route()->getName() == 'admin.dashboard' ) 
<!-- //Multiselect Css -->
<link rel="stylesheet" href="{{ asset('adminassets/css/bootstrap-multiselect.css') }}">
@endif
@if( Request::is('admin')) 
<link rel="stylesheet" type="text/css" href="{{ asset('css/style.css?v=1.1') }}">
@endif
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/admin-style.css?v=1.1') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/admin-responsive.css?v=1.1') }}">
 <link rel="stylesheet" href="{{ asset('css/select2.min.css') }}"> 
<link rel="stylesheet" href="{{ asset('adminassets/css/jquery.mCustomScrollbar.min.css') }}">

@if( Request::route()->getName() == 'admin.appointments' )  
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/calendar-main.css') }}">
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/bootstrap-float-label.min.css') }}">
@endif
@if( Request::route()->getName() == 'admin.appointments'  || Request::route()->getName() == 'admin.reports' || Request::route()->getName() == 'admin.land-listing' || Request::route()->getName() == 'admin.payments' || Request::route()->getName() == 'admin.rating-and-review' || Request::route()->getName() == 'admin.messages' || Request::route()->getName() == 'admin.your-profile')  
@endif
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css" />
<!-- <link href="{{ asset('adminassets/css/gijgo.min.css') }}" rel="stylesheet" type="text/css" /> -->
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.css" rel="stylesheet" type="text/css" />


@if( Request::route()->getName() == 'admin.reports' )  
<link rel="stylesheet" type="text/css" href="{{ asset('adminassets/css/owl.carousel.css') }}">
@endif
 <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css"> 

<script type="text/javascript" src="{{ asset('adminassets/js/jquery.min.js') }}"></script>
<link rel="stylesheet" href="{{ asset('upload/css/jquery.fileupload.css') }}">
<link rel="stylesheet" href="{{ asset('upload/css/jquery.fileupload-ui.css') }}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<link rel="stylesheet" href="{{ asset('adminassets/css/jquery.timepicker.min.css')}}"/>
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="base_url" content="{{ url('/') }}">

resources/views/admin/partials/header.blade.php
<link rel="stylesheet" type="text/css" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
<style>
    #toast-container > .toast-info{
        background-image: none !important;
    }
    #toast-container > .toast-warning{
        content: "";
        background-image: none !important;
    }
    #toast-container > .toast-success{
        content: "";
        background-image: none !important;
    }

</style>

@php
$notifications = notificationData('admin');

@endphp
<script>
    $(document).ready(function () {
        toastr.options = {
            timeOut: 0,
            extendedTimeOut: 0,
            "positionClass": "toast-bottom-right",
        };
        toastr.options.closeButton = true;
<?php
if (count($notifications)) {
    foreach ($notifications as $noti) {
        ?>
                toastr.options.closeHtml = '<button class="text-white markReadNoti" data-id="<?php echo $noti->id ?>">×</button>';
                toastr.info("{{ $noti->message}}");
    <?php }
}
?>
        $('.markReadNoti').on('click', function () {
            var id = $(this).data('id');
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });
            $.ajax({
                type: "get",
                url: "mark-read-notification/" + id,

                success: function (data) {
                }
            });
        });
    });
</script>
<a href="javascript:void(0);" class="hamburgerMenu"></a>
<div class="mobileLogo">
    <a href="index.html">
        <img src="{{ asset('adminassets/images/logo.svg') }}" alt="Know your Land" /> 
    </a>
</div>

<div class="headRightLinks">
    <a href="javscript:void(0);" class="notificationLink" id="headNotiDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @if(count($notifications))
        <span>{{ count($notifications) }}</span>
        @endif
        <img src="{{ asset('adminassets/images/svg-icons/noti-icon.svg') }}" alt="notification" />
        <em>Notifications</em>
    </a>             
    <div class="dropdown-menu notificationDropdown" aria-labelledby="headNotiDropdown">
        @if(count($notifications))
        @foreach($notifications as $noti)
        <div class="notiData">
            @php
            if(!empty($noti->apppointment_id)){
            $url = url('admin/appointments');
            }elseif(!empty($noti->property_id)){
            $url = url('admin/land-listing');
            }elseif(!empty($noti->land_report_id)){
            $url = url('admin/reports');
            }elseif(!empty($noti->service_enquiry_id)){
            $url = url('admin/service-enquiry');
            }else{
            $url = url('admin/dashboard');
            }
            @endphp
            <a href="{{ $url }}">
                {{ $noti->message }}</a>

        </div>
        @endforeach
        @endif

    </div> 

    <a href="javscript:void(0);">
        @php
        $path = asset('broker/images/svg-icons/user-icon.svg');
        if(Storage::disk('admin')->exists(str_replace('admin_image', '', auth()->user()->photo)))
        {
        $path = Storage::disk('admin')->url(str_replace('admin_image/', '', auth()->user()->photo));
        }
        @endphp
        <img class="rounded-circle" src="{{ $path }}" alt="User" />
        <em class="headerUserName">His, {{ auth()->user()->name }}</em>
    </a>
</div>

resources/views/admin/partials/javascripts.blade.php
<script type="text/javascript" src="{{ asset('adminassets/js/popper.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('adminassets/js/bootstrap.min.js') }}"></script>
<!-- //Magnific Popup JS -->
<script type="text/javascript" src="{{ asset('adminassets/js/jquery.magnific-popup.min.js') }}"></script>

<script type="text/javascript" src="{{ asset('adminassets/js/jquery.mCustomScrollbar.concat.min.js') }}"></script>

<!-- //Multiselect JS -->
<script src="{{ asset('adminassets/js/bootstrap-multiselect.js') }}"></script>

<script type="text/javascript" src="{{ asset('adminassets/js/gijgo.min.js') }}"></script>

@if( Request::route()->getName() == 'admin.appointments' )  
<!--<script type="text/javascript" src="{{ asset('adminassets/js/calendar-main.js') }}"></script>-->

@endif

<script type="text/javascript" src="{{ asset('adminassets/js/owl.carousel.js') }}"></script>

@if( Request::route()->getName() == 'admin.messages' )
<script src="{{ asset('adminassets/js/jquery.mockjax.jss') }}"></script>
<script src="{{ asset('adminassets/js/autoselectdd-bootstrap-typeahead.js') }}"></script>
@endif
<script type="text/javascript" src="{{ asset('adminassets/js/admin-custom.js') }}"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> 
<script type="text/javascript" src="{{ asset('adminassets/js/gijgo.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/vendor/jquery.ui.widget.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/load-image.all.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/canvas-to-blob.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/jquery.fileupload.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/jquery.fileupload-process.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/jquery.fileupload-validate.js') }}"></script>
<script type="text/javascript" src="{{ asset('upload/js/jquery.fileupload-image.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
<!--<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>-->
<script type="text/javascript" src="{{ asset('js/Chart.js') }}"></script>
<script src="{{ asset('adminassets/js/jquery.timepicker.min.js')}}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>

<!-- 
 <script type="text/javascript" src="{{ asset('adminassets/js/owl.carousel.js') }}"></script>
<script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script> -->

resources/views/admin/partials/sidebar.blade.php
 <a href="javascript:void(0);" class="hamburgerMenu"></a>
            <div class="sidebarLogo">
                <a href="{{ route('admin.dashboard') }}">
                    <img src="{{ asset('adminassets/images/logo.svg') }}" alt="Know your Land" />
                    <span>Know your Land</span>
                </a>
            </div><!--//sidebarLogo-->

            <div class="sideNavigation customScrollbar">
                <ul>
                    <li><a href="{{ route('admin.dashboard') }}" class="nav_dashboard @if( Request::route()->getName() == 'admin.dashboard' ) active @endif">Dashboard</a></li>
        @php
        $appointment = secondaryAdminPermission(3);
        @endphp
        @if(auth()->user()->id == 1 || !empty($appointment))
                    <li><a href="{{ route('admin.appointments') }}" class="nav_appoint @if( Request::route()->getName() == 'admin.appointments' ) active @endif">Appointments</a></li>
        @endif

        @php
        $reports = secondaryAdminPermission(1);
        @endphp
        @if(auth()->user()->id == 1 || !empty($reports))
                    <li><a href="{{ route('admin.reports') }}" class="nav_reports @if( Request::route()->getName() == 'admin.reports' ) active @endif">Reports</a></li>
        @endif
        @php
        $land = secondaryAdminPermission(2);
        @endphp
        @if(auth()->user()->id == 1 || !empty($land))
                    <li><a href="{{ route('admin.land-listing') }}" class="nav_land  @if( Request::route()->getName() == 'admin.land-listing' ) active @endif">Land Listing</a></li>
        @endif

        @if(auth()->user()->id ==1)
                    <li><a href="{{ url('admin/pages') }}" class="nav_land  @if( request()->is('admin/pages', 'admin/page-create', 'admin/edit-page/*') ) active @endif">Pages</a></li>
                    <li><a href="{{ route('admin.experts') }}" class="nav_experts @if( Request::route()->getName() == 'admin.experts' ) active @endif">Experts</a></li>
                    <li><a href="{{ route('admin.users') }}" class="nav_profile @if( Request::route()->getName() == 'admin.users' ) active @endif">Users</a></li>
                    <li><a href="{{ route('admin.brokers') }}" class="nav_experts @if( Request::route()->getName() == 'admin.brokers' ) active @endif">Brokers</a></li>
                    <li><a href="{{ url('admin/value-added-services') }}" class="nav_experts @if( request()->is('admin/experts-value-added-services')  ) active @endif">Value Added Services</a></li>
                    <li><a href="{{ route('admin.service-enquiry') }}" class="nav_rating @if( Request::route()->getName() == 'admin.service-enquiry' ) active @endif">Service Enquiries</a></li>
                    <li><a href="{{ route('admin.payments') }}" class="nav_payments @if( Request::route()->getName() == 'admin.payments' ) active @endif">Payments</a></li>
                    <li><a href="{{ route('admin.rating-and-review') }}" class="nav_rating @if( Request::route()->getName() == 'admin.rating-and-review' ) active @endif">Rating & Reviews</a></li>
                    <li><a href="{{ route('admin.messages') }}" class="nav_msg @if( Request::route()->getName() == 'admin.messages' ) active @endif">Message</a></li>
        @endif
                    <li><a href="{{ route('admin.your-profile') }}" class="nav_profile  @if( Request::route()->getName() == 'admin.your-profile' ) active @endif">Your Profile</a></li>
                    <li><a href="{{ route('admin.adminlogout') }}" class="nav_logout">Logout</a></li>
                </ul>
            </div><!--//navigation-->
@if(auth()->user()->id ==1)
            <div class="addSecondAdminBtn" id="inline-popups">
                <!--<a href="#secondary-Admin-popup" data-effect="mfp-zoom-in" class="btn btn-primary">Add Secondary Admin</a>-->
    <a href="#secondary-Admin-popup" data-effect="mfp-zoom-in" class="btn btn-primary secondaryAdminAddButton">Add Secondary Admin</a>
            </div>
@endif